<script setup lang="ts">
import { PhArrowRight, PhFileZip, PhGitBranch, PhUploadSimple, PhWarning } from '@phosphor-icons/vue'
import { ref } from 'vue'
import { getScanStatus, scanGit, scanZip } from '../api'
const emit=defineEmits<{complete:[analysisId:number];close:[]}>()
const mode=ref<'git'|'zip'>('git');const url=ref('');const file=ref<File>();const running=ref(false);const error=ref('');const phase=ref('')
const pause=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms))
function choose(candidate?:File){if(!candidate)return;file.value=candidate;error.value=''}
async function submit(){running.value=true;error.value='';phase.value=mode.value==='git'?'正在克隆仓库':'正在上传源码';try{const queued=mode.value==='git'?await scanGit(url.value):await scanZip(file.value!);phase.value='正在解析模块与依赖';for(let i=0;i<240;i+=1){await pause(750);const task=await getScanStatus(queued.task_id);if(task.status==='success'&&task.result?.analysis_id){emit('complete',task.result.analysis_id);return}if(task.status==='failure')throw new Error(task.error||'代码扫描失败')}throw new Error('仓库仍在分析，请稍后重试。')}catch(cause){error.value=(cause as Error).message}finally{running.value=false;phase.value=''}}
</script>
<template><section class="repository-workspace"><header class="intake-head"><div><h1>接入代码仓库</h1><p>把源码转换成可探索的模块依赖、复杂度和风险证据。</p></div><button class="text-action" @click="emit('close')">返回架构图谱</button></header><div v-if="error" class="intake-error" role="alert"><PhWarning :size="18"/><span>{{error}}</span></div><div class="source-switch" role="tablist"><button :class="{active:mode==='git'}" role="tab" :aria-selected="mode==='git'" @click="mode='git'"><PhGitBranch :size="18"/>公开 Git 仓库</button><button :class="{active:mode==='zip'}" role="tab" :aria-selected="mode==='zip'" @click="mode='zip'"><PhFileZip :size="18"/>上传 ZIP</button></div><div class="intake-body"><div v-if="mode==='git'" class="git-source"><label for="repository-url">GitHub / Gitee 仓库地址</label><div><input id="repository-url" v-model.trim="url" type="url" placeholder="https://gitee.com/owner/repository.git" @keydown.enter="url&&!running&&submit()"/><button :disabled="!url||running" @click="submit">{{running?phase:'开始分析'}}<PhArrowRight :size="17"/></button></div><p>仅支持公开 HTTPS 仓库。扫描时使用浅克隆，不读取账号凭据。</p></div><div v-else class="zip-source"><label class="repo-drop"><input type="file" accept=".zip" @change="choose(($event.target as HTMLInputElement).files?.[0])"/><PhUploadSimple :size="30" weight="duotone"/><strong>{{file?.name||'选择项目 ZIP 压缩包'}}</strong><span>{{file?`${(file.size/1024/1024).toFixed(2)} MB`:'最大 100 MB'}}</span></label><button class="submit-source" :disabled="!file||running" @click="submit">{{running?phase:'上传并分析'}}<PhArrowRight :size="17"/></button></div><aside class="scan-scope"><h2>本次会分析什么</h2><dl><div><dt>语言</dt><dd>Java、Python</dd></div><div><dt>结构</dt><dd>模块、导入与双向依赖</dd></div><div><dt>度量</dt><dd>有效代码行、圈复杂度、连接度</dd></div><div><dt>输出</dt><dd>依赖图、风险队列、热点文件</dd></div></dl><p>上传文件只在任务期间保存，分析完成后自动清理源码。</p></aside></div></section></template>
